### ISSUE TITLE
Error messages on rclouddocs/Introduction to wdcplot

### ISSUE THREAD

**Issue by rhknag** [cscheid/rserve-js#19]
I got this error and Error in fun(...) atempt to apply non function when running "Inroduction to wdcplot" after executing a number of notebooks.  In a new tab it worked.

Error: Mismatched anonymous define() module: [object Object]
http://requirejs.org/docs/errors.html#mismatch
at makeError (https://rcloud.research.att.com/lib/js/require.js:166:17)
at intakeDefines (https://rcloud.research.att.com/lib/js/require.js:1221:36)
at Object.localRequire [as require](https://rcloud.research.att.com/lib/js/require.js:1402:21)
at requirejs (https://rcloud.research.att.com/lib/js/require.js:1737:24)
at Function.req.config (https://rcloud.research.att.com/lib/js/require.js:1745:16)
at eval (dcplot.js:3:11)
at eval (dcplot.js:43:3)
at rcloud.setup_js_installer.install_js (https://rcloud.research.att.com/js/rcloud_bundle.js:279:34)
at WebSocket.socket.onmessage (https://rcloud.research.att.com/

**Comment by gordonwoodhull** [comment]
This issue was moved to att/rcloud.dcplot#20

**Comment by gordonwoodhull** [comment]
I don't have write access to this repo, but this looks like very much an rcloud.dcplot bug rather than an rserve.js bug... Please close.
